version: '3.7'

services:
  midnightboard:
    image: midnightboard
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 1337:1337
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=secret2020
      - POSTGRES_DB=midnightboard
    ports:
      - 5432:5432